#!/bin/bash
# Bashtuner V2.0 by Born2Root
# Play Internet Radio from Linux Command Line

#====> Define Paths

# Path to radio station list
pfadsender="$HOME/Programme/bashtuner/sender.csv" ; 

# Path to Logfile and temporary picture save location (album covers)
config_dir=~/.bash_radio
fifo=$config_dir/fifo
image_file=$config_dir/image
log_file=$config_dir/log


#====> Main Program

if [ ! -d $config_dir ]; then
    mkdir $config_dir
fi

if [ ! -p $fifo ]; then
    mkfifo $fifo
fi

trap "rm -f $fifo" INT TERM EXIT


playradio() {
auswahl=$(awk -F "	" '{print $1"\n"$2}' $pfadsender | zenity --list --hide-column=1 --column "Nummer" --column "Sender" --title="Bashtuner" --ok-label="Abspielen" --cancel-label="Exit" --text="Radiosender einschalten" --width=600 --height=300)
if [ $? = "1" ] ; then exit 1 ; else
export play=$(cat $HOME/Programme/bashtuner/sender.csv | head -n"$auswahl" | tail -n1 | cut -d'	' -f3)

mplayer $play 2> /dev/null | awk -F\' '/StreamTitle/ {print $2}'

#print current played song to terminal
echo 'message:' | zenity --notification --listen


#wait
playradio
fi
}
playradio
